name: Daily Script

on:
  schedule:
    - cron: '*/30 * * * *' # runs every half an hour

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1


      - name: Run script
        run: |
          # replace this with the command to run your script
          echo "Running my daily script"
