name: Cron job
on:
  schedule:
    - cron: '*/1 * * * *' # Runs every day at midnight UTC
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Print
        run: echo hello world
